[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "konlpy>=0.6.0",
    "numpy>=2.3.2",
    "pytest>=8.4.2",
]
